backend:
  name: git-gateway
  branch: dev/11ty
media_folder: "_site/img/uploads"
public_folder: "img/uploads"

collections:
  - name: "pages"
    label: "Σελίδες"
    files:
      - label: "Βίντεο Αρχικής Σελίδας"
        name: "livestream"
        file: "_includes/live.html"
        fields:
          - {label: "Κώδικας Facebook", name: "body", widget: "text"}
