backend:
  name: git-gateway
  branch: dev/11ty
media_folder: "_site/img/uploads"
public_folder: "img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Livestream video"
        name: "livestream"
        file: "_includes/live.html"
        fields:
          - {label: "Facebook Video", name: "fb-video", widget: "text"}
